server:
  port: 8080

spring:
  application:
    name: betting-service

  datasource:
    url: jdbc:h2:mem:bettingdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bet-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: bet-producer-group
  consumer:
    group: bet-consumer-group
